### ISSUE TITLE
Is this patched for good?

### ISSUE THREAD

**Issue by claytann** [eemj/free-ghillieglade-tp#7]
Hey Jamie, I heard that teleporting has been patched on EU, and soon to be patched on NA too. Do you know what's going on? I'm curious, if they really patched it, how did they do it?

**Comment by eemj** [comment]
They did yeah I'm not sure though I don't really play the game anymore.. I've been told they split the packets into 3 parts (one for Highwatch, one for Vanguard Quests and the other one for NPCs).. If there's a way that this could be fixed my guess would be defining the C_REQUEST_TELEPORT_TO_NPC (or something like that..) and try to send a request to Ghillieglade's Teleportal (since teleports are NPC's iirc..)

**Comment by claytann** [comment]
Ohh I see, that makes sense. I was wondering why would they fix the teleporting and leave the projectile exploits working.
Thanks for the quick response, man.

**Comment by eemj** [comment]
I guess the projectile exploits would be next..
You're welcome.
